version: "3.8"
services:
  web:
    build:
      context: ./
      target: development
    volumes:
      - .:/src
    command: yarn start
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
